class RiskRules:
    MAX_PORTFOLIO_RISK = 0.05
    RISK_PER_TRADE = 0.01
    MAX_SYMBOL_RISK = 0.02
    MAX_GROUP_RISK = 0.04
    MAX_POSITIONS = 10

    SLIPPAGE_BUFFER = 1.1

    DAILY_LOSS_LIMIT = 0.03
    MAX_DRAWDOWN = 0.10
